### ISSUE TITLE
gui-lib issues

### ISSUE THREAD

**Issue by shakna-israel** [mbutterick/beautiful-racket#1]
Hi, I'm running Racket v6.5, but I'm having issues with this library.

```
gui-lib (have 1.24, need 1.26)
```

Unfortunately, gui-lib is in the installation scope, so doesn't get automatically updated.

And updating it doesn't seem to work either:

```
$ raco pkg update -i gui-lib
> No updates available
```

Would you be able to point me in the right direction?

**Comment by mbutterick** [comment]
I removed the dependency on `gui-lib` 1.26. If you update the package it should work with v6.5.
