### ISSUE TITLE
Can't send feedback

### ISSUE THREAD

**Issue by sean-bennett112** [mbutterick/beautiful-racket#11]
Hi, I was trying to send feedback with the included comment section, but it looks like you're trying to request a rkt file over mixed HTTP when posting a comment, and Chrome is blocking it. Here's the whole error message in the developer console:

```
VM131:1 Mixed Content: The page at 'https://beautifulracket.com/jsonic/the-tokenizer.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://beautifulracket.com/scripts/poster.rkt'. This request has been blocked; the content must be served over HTTPS.
```

Thanks so much for the book, really enjoying it!

**Comment by mbutterick** [comment]
Sorry, switching over to `https` this weekend and broke a couple things. Line 72 [of this file](https://beautifulracket.com/functions.js) should now show an `https` link, which I believe repairs the problem.

**Comment by mbutterick** [comment]
PS Glad you’re enjoying :metal:

**Comment by sean-bennett112** [comment]
Yep, looks like feedback is successfully sent on my end after a hard reload of the Chrome tab. Thanks!
