### ISSUE TITLE
Online REPL

### ISSUE THREAD

**Issue by stereobooster** [mbutterick/beautiful-racket#12]
You made a beautiful thing. It would be even more fantastic if there would be online IDE in which user can start to practice without a need to setup something. Like https://glitch.com/ or https://thimble.mozilla.org or https://codepen.io/ or https://codesandbox.io/

**Comment by mbutterick** [comment]
I agree. I looked into that option early on. Racket has http://pasterack.org/, but I would’ve needed something more elaborate. I have no idea how to build something like that. Nor does *Beautiful Racket* generate enough money to let me pay someone else to build it. Maybe someday.
