### ISSUE TITLE
safari for ios warns the beautifulracket.com certificate expired?

### ISSUE THREAD

**Issue by spdegabrielle** [mbutterick/beautiful-racket#17]
Sorry didnt get a screenshot.

**Comment by celtic-coder** [comment]
There does not appear to be any issue with the certificate as per https://www.ssllabs.com/ssltest/analyze.html?d=beautifulracket.com. There is a mismatch with the alternative name of "pollenpub.com" but otherwise everything looks fine.

**Comment by mbutterick** [comment]
Seems OK now.
