### ISSUE TITLE
Errors during package install

### ISSUE THREAD

**Issue by thelonious** [mbutterick/beautiful-racket#18]
I'm running on macOS 10.14.4 and wanted a clean/fresh DrRacket environment. I did the following:
- deleted ~/Applications/DrRacket
- deleted ~/Library/Racket
- deleted all PL and racket files from ~/Library/Application Support/Preferences
- re-installed DrRacket

When I try to install beautiful-racket from the command-line using the following

```bash
raco pkg install --auto beautiful-racket
```

I get all sorts of errors during the install. The first error looks like this:

```
standard-module-name-resolver: collection not found
  for module path: brag/lang/reader
  collection: "brag/lang"
  in collection directories:
  ...
```

Other errors report not being able to open a module file.

```
open-input-file: cannot open module file
  module path: brag/support
  path: /Users/kevin/Library/Racket/7.2/pkgs/brag/support.rkt
  system error: no such file or directory; rktio_err=3
```

I verified that file is not present on my drive, but I suspect I'm getting a cascade of errors due to the initial error.

If I test the beautiful-racket install via `racket -l br/test`, I get a message that it has installed correctly; however, with all of the errors I'm seeing, I'm not sure if I can trust that :). Perhaps my DrRacket install is hosed.

Thanks!

**Comment by mbutterick** [comment]
Sorry about that. I rearranged the `brag` repo today and forgot to update the URL on the Racket package server. I just did that, and reinstalled successfully, so let me know if it works for you.

**Comment by thelonious** [comment]
No worries. Works like a charm! Thanks for the quick response and the quick fix!
