### ISSUE TITLE
Any thoughts on localization?

### ISSUE THREAD

**Issue by obonac** [mbutterick/beautiful-racket#24]
Hi,

I am new to racket (some scheme and lisp background).

Whats the best way to localize the demos?

See https://github.com/djinn/khhota as a initial effort

Regards,
Abhishek

**Comment by mbutterick** [comment]
I don’t know anything about localization. 

I suppose I would go into the `lexer.rkt` and translate the English-language tokens to the new language. In the case of `reserved-terms`, the lexer could convert the reserved term in the new language to its English equivalent before emitting a token (which would contain the original English). Thus the lexer would act as a translation layer, in effect. 

By keeping the localization in one file, it would be easier to create a system where you could support multiple localizations.

But I’m just guessing. Beyond that, it would be experimentation and refinement.
