### ISSUE TITLE
contract violation when running #lang reader stacker-demo/stacker

### ISSUE THREAD

**Issue by antonmosin** [mbutterick/beautiful-racket#25]
In the first tutorial, I encounter an error on MacOS when running this command:

`#lang reader stacker-demo/stacker`

```
 Library/Racket/8.3/pkgs/beautiful-racket-demo/stacker-demo/stacker.rkt:14:5: first: contract violation
  expected: (and/c list? (not/c empty?))
  given: '()
```
 which seems to originate [here](https://github.com/mbutterick/beautiful-racket/blob/b0d133f4ba4149ea506d8b0dbd3845c915efdd06/beautiful-racket-demo/stacker-demo/stacker.rkt#L14)

My installation seems to be correct, as`racket -l br/test`  returned `You installed beautiful-racket v1.6 correctly.` and I can run `#lang br,` `#lang br/quicklang` without problems. I've also set the `#lang br` to be default as suggested in the tutorial.

**Comment by mbutterick** [comment]
I believe you’re getting that error because you’re running the program without any input. What happens when you run the [actual sample program](https://beautifulracket.com/stacker/intro.html#a_V7pxH)?

```
#lang reader stacker-demo/stacker
4
8
+
3
*
```

**Comment by antonmosin** [comment]
Thank you very much for the prompt reply, @mbutterick: you're right, it works! Sorry for the false alarm, I  didn't realise that it doesn't work with empty input.
