### ISSUE TITLE
Wrong link to ragg in racketcon.html

### ISSUE THREAD

**Issue by kasbah** [mbutterick/beautiful-racket#3]
Hey, thanks for writing this book!

I noticed the ragg link is wrong on http://beautifulracket.com/appendix/racketcon.html

While searching for it I was thinking it might be good idea to link to this repo somewhere prominent (maybe I missed it). 

While I have your attention: epub or mobi formats are not available/output-able are they?

**Comment by mbutterick** [comment]
> I noticed the ragg link is wrong on http://beautifulracket.com/appendix/racketcon.html

Thanks. Fixed.

> While searching for it I was thinking it might be good idea to link to this repo somewhere prominent (maybe I missed it).

Fair suggestion. [Link added](http://beautifulracket.com/appendix/setup.html#how-to-report-problems).

> While I have your attention: epub or mobi formats are not available/output-able are they?

No. AFAIK nothing has changed that would affect [my existing argument against them](http://practicaltypography.com/why-theres-no-e-book-or-pdf.html).

**Comment by kasbah** [comment]
Fair enough, thanks for responding and fixing. I mainly like e-book formats because they let me sit in the sun while reading about programming even if the presentation isn't perfect.
