### ISSUE TITLE
SVG on Beautiful Racket home page crashes Windows Firefox sometimes

### ISSUE THREAD

**Issue by jpeinelt** [mbutterick/beautiful-racket#4]
When I try to open  http://beautifulracket.com with Firefox 50.1.0 on Windows 10 I get a spinning wheel and the browser does not react (it's reproducible on my machine).
Chrome works fine.

**Comment by mbutterick** [comment]
I’ve gotten a couple reports about this but I can’t reproduce it on any version of Firefox on Windows 10. It seems to have something to do with the SVG at the top.

**Comment by celtic-coder** [comment]
It's also a problem on Waterfox (64-bit version of FireFox) version 50.1.0 on Window 7 Professional. Going to http://beautifulracket.com/#appendix on the home page works fine, but scrolling to the graphic hangs the entire application.

**Comment by mbutterick** [comment]
I guess I'll just display a PNG to Firefox? I don’t know what else to do with this. It’s a vanilla SVG, and there are no reports that it causes problem in anything but Windows Firefox/Waterfox.

**Comment by jpeinelt** [comment]
It seems I will have some spare time tomorrow, I will try to debug it as good as possible and report back.

**Comment by mbutterick** [comment]
I suppose I should ask: are you running any extensions, like an ad blocker? I’ve never been able to reproduce this problem. But I also use a completely clean installation of Firefox. If the problem were tied to some common third-party Firefox extension, then everything would make sense.

**Comment by celtic-coder** [comment]
I have no extensions and only VLC and Shockwave Flash plugins. I use [Admuncher](https://www.admuncher.com) ad blocker across all browsers. Waterfox still hung when attempting to display the SVG on the home page with AdMucher turned off.

**Comment by jpeinelt** [comment]
I have uBlock origin, 1Password and Evernote. I disabled all which lead to a state where some text got displayed but FF still hanged. I could not debug it but opening the svg only did not crash the browser.

**Comment by zenspider** [comment]
Has anyone reported this on firefox? That's where the real problem lies assuming this is well formed SVG.

**Comment by jpeinelt** [comment]
not yet, I will try to write one :)

**Comment by mbutterick** [comment]
Don’t hold your breath. This [ligature bug](https://bugzilla.mozilla.org/show_bug.cgi?id=479829) was reported in 2009 and still hasn’t been fixed (and people still email me, believing it to be my fault) 🙀

**Comment by celtic-coder** [comment]
I noticed today that the home page no longer causes a problem for Waterfox. Matthew, did you make changes to the SVG, perhaps? If so, thanks!

**Comment by mbutterick** [comment]
The power of procrastination.

**Comment by mbutterick** [comment]
I just refreshed the home page SVG. I'm interested to hear if anyone on this issue is still seeing a problem with Windows Firefox. I am not (but then I never did)

**Comment by jpeinelt** [comment]
No problem on my side. Configuration as before but FF 52.0

Nice! and thanks for the book!
