### ISSUE TITLE
Confusing error for `(define-macro (id x ...) ....)`

### ISSUE THREAD

**Issue by bennn** [mbutterick/beautiful-racket#9]
When an ellipses follows a non-wildcard variable, `define-macro` can give a strange error message. E.g.:

```
#lang racket/base
(require br/define (for-syntax racket/base))

(define-macro (my-begin x ...)
  #'(begin x ...))
```

Error message:
```
$ raco make foo.rkt
foo.rkt:5:13: syntax: no pattern variables before ellipsis in template
  at: ...
  in: (begin x ...)
```

`define-macro` should warn about `...` that don't come after a wildcard (I think that's the only place they're allowed)

**Comment by mbutterick** [comment]
Closed by #10

**Comment by mbutterick** [comment]
> `define-macro` should warn about `...` that don't come after a wildcard (I think that's the only place they're allowed)

They are also allowed after subpatterns like `((X ...) ...)` Unfortunately your patch did not handle these correctly.

**Comment by mbutterick** [comment]
I believe f0ec809502bb980a97a0fdcf98942f19d9dfc37d does what you originally intended.
